import json
from modules.logging_config import logger
from modules.payload_loader import get_payload_loader


class ScriptGenerator:
    def __init__(self, config):
        self.config = config
        self.output_dir = config.get("output_dir", "scripts")
        self._payload_loader = None
    
    @property
    def payload_loader(self):
        if self._payload_loader is None:
            self._payload_loader = get_payload_loader()
        return self._payload_loader
        
    def generate_idor_script(self, endpoint, findings):
        base_url = endpoint["url"].split("?")[0]
        params = endpoint.get("params", [])
        id_params = [p for p in params if any(x in p.lower() for x in ["id", "user", "uid", "account"])]
        
        if not id_params:
            return None
            
        param = id_params[0]
        
        script = f'''#!/usr/bin/env python3
"""
IDOR Enumeration Script for {base_url}
Generated by BugHunter AI
"""
import requests
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

TARGET = "{base_url}"
PARAM = "{param}"
SESSION = requests.Session()
SESSION.headers.update({{"User-Agent": "BugHunter-AI/v1.0"}})

PAYLOADS = [str(i) for i in range(1, 100)]

def test_id(payload):
    try:
        resp = SESSION.get(TARGET, params={{PARAM: payload}})
        return {{
            "payload": payload,
            "status": resp.status_code,
            "length": len(resp.text),
            "success": True
        }}
    except Exception as e:
        return {{"payload": payload, "error": str(e), "success": False}}

def main():
    print(f"[*] Testing IDOR on {{TARGET}}")
    print(f"[*] Parameter: {{PARAM}}")
    
    results = []
    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = [executor.submit(test_id, p) for p in PAYLOADS]
        for future in as_completed(futures):
            result = future.result()
            if result["success"]:
                results.append(result)
                print(f"[{{result['status']}}] payload={{result['payload']}} len={{result['length']}}")
    
    print(f"\\n[*] Completed. {{len(results)}} responses analyzed")

if __name__ == "__main__":
    main()
'''
        return script
    
    def generate_xss_script(self, endpoint, findings):
        base_url = endpoint["url"].split("?")[0]
        params = endpoint.get("params", [])
        
        if not params:
            return None
            
        param = params[0]
        
        xss_payloads = self.payload_loader.get_payload_values("xss", level="basic", limit=10)
        
        if not xss_payloads:
            try:
                xss_payloads = self.payload_loader.get_payload_values("xss", level="intermediate", limit=5)
            except Exception:
                xss_payloads = []
        
        payload_json = json.dumps(xss_payloads)
        
        script = f'''#!/usr/bin/env python3
"""
XSS Payload Tester for {base_url}
Generated by BugHunter AI
"""
import requests
import sys

TARGET = "{base_url}"
PARAM = "{param}"
SESSION = requests.Session()
SESSION.headers.update({{"User-Agent": "BugHunter-AI/v1.0"}})

PAYLOADS = {payload_json}

def test_xss(payload):
    try:
        resp = SESSION.get(TARGET, params={{PARAM: payload}})
        reflected = payload in resp.text
        
        return {{
            "payload": payload,
            "status": resp.status_code,
            "reflected": reflected,
            "vulnerable": reflected
        }}
    except Exception as e:
        return {{"payload": payload, "error": str(e)}}

def main():
    print(f"[*] Testing XSS on {{TARGET}}")
    print(f"[*] Parameter: {{PARAM}}")
    print(f"[*] Testing {{len(PAYLOADS)}} payloads\\n")
    
    for payload in PAYLOADS:
        result = test_xss(payload)
        status = "VULN" if result.get("vulnerable") else "SAFE"
        print(f"[{{status}}] {{result['payload']}}")

if __name__ == "__main__":
    main()
'''
        return script
    
    def generate_sql_injection_script(self, endpoint, findings):
        base_url = endpoint["url"].split("?")[0]
        params = endpoint.get("params", [])
        
        if not params:
            return None
            
        param = params[0]
        
        sqli_payloads = []
        try:
            sqli_payloads = self.payload_loader.get_payload_values("sql-injection", level="basic", limit=10)
        except Exception:
            sqli_payloads = []
        
        if not sqli_payloads:
            try:
                sqli_payloads = self.payload_loader.get_payload_values("sql-injection", level="intermediate", limit=5)
            except Exception:
                sqli_payloads = []
        
        if not sqli_payloads:
            sqli_payloads = ["'", "' OR '1'='1"]
        
        payload_json = json.dumps(sqli_payloads)
        
        script = f'''#!/usr/bin/env python3
"""
SQL Injection Tester for {base_url}
Generated by BugHunter AI
"""
import requests
import time
import sys

TARGET = "{base_url}"
PARAM = "{param}"
SESSION = requests.Session()
SESSION.headers.update({{"User-Agent": "BugHunter-AI/v1.0"}})

PAYLOADS = {payload_json}

SQL_ERRORS = ["sql syntax", "mysql", "postgresql", "ora-", "unterminated", "warning"]

def test_sql(payload):
    start = time.time()
    try:
        resp = SESSION.get(TARGET, params={{PARAM: payload}})
        elapsed = time.time() - start
        
        errors_found = [e for e in SQL_ERRORS if e in resp.text.lower()]
        
        return {{
            "payload": payload,
            "status": resp.status_code,
            "length": len(resp.text),
            "errors": errors_found,
            "time": elapsed,
            "potential": bool(errors_found) or elapsed > 3
        }}
    except Exception as e:
        return {{"payload": payload, "error": str(e)}}

def main():
    print(f"[*] Testing SQL Injection on {{TARGET}}")
    print(f"[*] Parameter: {{PARAM}}\\n")
    
    for payload in PAYLOADS:
        result = test_sql(payload)
        if result.get("errors"):
            print(f"[VULN] {{payload}} - Errors: {{result['errors']}}")
        elif result.get("time", 0) > 3:
            print(f"[TIME] {{payload}} - {{result['time']:.2f}}s")
        else:
            print(f"[SAFE] {{payload}}")

if __name__ == "__main__":
    main()
'''
        return script
    
    def generate_full_script(self, findings, score_results):
        vuln_types = [f.get("type") for f in findings]
        
        script = f'''#!/usr/bin/env python3
"""
BugHunter AI - Auto-Generated Security Test Script
Severity: {score_results.get("severity", "unknown")}
Score: {score_results.get("score", 0)}
"""
import requests
import sys

TARGET = "{{TARGET}}"
SESSION = requests.Session()
SESSION.headers.update({{"User-Agent": "BugHunter-AI/v1.0"}})

VULNERABLE_TO = {json.dumps(vuln_types)}

def main():
    print(f"[*] BugHunter AI Security Test")
    print(f"[*] Target: {{TARGET}}")
    print(f"[*] Vulnerabilities: {{', '.join(VULNERABLE_TO)}}")
    print("[*] Implement test logic for each vulnerability type")

if __name__ == "__main__":
    main()
'''
        return script
    
    def save_script(self, script, filename):
        try:
            path = f"{self.output_dir}/{filename}"
            with open(path, "w") as f:
                f.write(script)
            logger.info(f"Script saved: {path}")
            return path
        except Exception as e:
            logger.error(f"Script save error: {e}")
            return None
    
    def generate_all_scripts(self, endpoint, findings, score_results):
        scripts = {}
        
        for finding in findings:
            vtype = finding.get("type")
            
            if vtype == "idor" and "idor" not in scripts:
                script = self.generate_idor_script(endpoint, findings)
                if script:
                    scripts["idor"] = script
                    
            elif vtype == "xss" and "xss" not in scripts:
                script = self.generate_xss_script(endpoint, findings)
                if script:
                    scripts["xss"] = script
                    
            elif vtype == "sql_injection" and "sql_injection" not in scripts:
                script = self.generate_sql_injection_script(endpoint, findings)
                if script:
                    scripts["sql_injection"] = script
        
        if not scripts:
            scripts["general"] = self.generate_full_script(findings, score_results)
            
        return scripts


def generate_scripts(config, endpoint, findings, score_results):
    generator = ScriptGenerator(config)
    return generator.generate_all_scripts(endpoint, findings, score_results)